### ISSUE TITLE
Wrong type of Value in Field_Instance 

### ISSUE THREAD

**Issue by ormanbai123** [jakubtomsu/odin-ldtk#2]
I have an Entity in LDTK with custom field for velocity, which is of type Array\<Float\>. When I tried to parse and get those values with Odin's type switch statement I could not get them by Floats, but instead got them as Integers. Am I doing something wrong here?

Here is data in the .ldtk file:
![Screenshot (99)](https://github.com/user-attachments/assets/aa73886d-52db-469c-a1f5-eeb5d89700c7)

This is my code:
![Screenshot (102)](https://github.com/user-attachments/assets/d1e1e278-6c5f-42e7-b2d6-a856bf65801b)

And this is the result I am getting now:
![res](https://github.com/user-attachments/assets/4fe99ecc-2ac4-4094-b308-cb7540116cb0)

**Comment by jakubtomsu** [comment]
Unfortunately I believe that's because of the way json parser deals with numerical values. It doesn't know anything about the `Array<Float>`, it just sees `150`, `288` etc so it loads them as intergers. `ldtk.load_from_memory` calls `json.unmarshal` which calls `json.unmarshal_any`. This makes a parser with a hardcoded `parse_integers = true` flag. That's the correct behavior for general use cases though, so what you probably want to do instead is to make a small proc to handle the conversions in a nice way. Something like this:

```odin
load_number :: proc($T: typeid, val: json.Value) -> T
where intrinsics.type_is_integer(T) || intrinsics.type_is_float(T) {
    switch v in val {
    case json.Float: return T(v)
    case json.Integer: return T(v)
    case:
        assert(false, "Not a numeric value!")
        return 0
    }
}
```

And while you're at it you might also want to write another util proc for vectors:
```odin
load_vector :: proc($T: [$N]$V, val: json.Value) -> (result: T)
where intrinsics.type_is_integer(V) || intrinsics.type_is_float(V) {
    switch v in val {
    case json.Array:
        for field, i in v do result[i] = load_number(V, v)
    }
}
```

(note: I didn't test this code)
